# Introduction
This notebook will contain different API-calling tests for our ATS systems.

In [2]:
# setup
import requests
import pandas as pd
from collections import defaultdict
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import time
from functools import reduce

session = requests.Session()
retries = Retry(total=3, backoff_factor=1, status_forcelist=[429, 500, 502, 503, 504])
session.mount('https://', HTTPAdapter(max_retries=retries))

# Greenhouse.io

In [3]:
# import greenhouse company list
greenhouse = pd.read_csv('../ats_companies/greenhouse.csv')
greenhouse.head()

          slug
0    0verwatch
1    103644278
2      10alabs
3     10beauty
4  10xgenomics

In [52]:
# define fetching scheme
def get_greenhouse(slug: str) -> dict:
    try:
        res = session.get(f'https://boards-api.greenhouse.io/v1/boards/{slug}/jobs')
        if res.ok:
            res_json = res.json()
            if res_json['meta']['total'] > 0:
                return res_json['jobs']
            else:
                return []
        elif res.status_code == 404:
            raise Exception('404 - job not found')
        else:
            raise Exception(res.status_code, '- error')
    except Exception as e:
        return str(e)

def scrape_greenhouse(
        df: pd.DataFrame, 
        limit: int= -1
    ) -> dict:
    '''Scrape greenhouse.io for jobs using a pd.DataFrame containing company slugs.'''
    # greenhouse.io defines no rate limit on their job board API, however they define a 50-per-10-second
    # limit on their audit log API, so we will respect this.
    # 5 per second, .2s delay
    # this takes about 50 minutes

    # --- create variables
    results = defaultdict()
    i = 0
    # stats
    valid = 0
    invalid = 0
    has_jobs = 0
    total_jobs = 0

    # --- begin scrape
    start_time = time.time()
    for slug in df.slug:
        if i == limit: break
        # - fetch
        res = get_greenhouse(slug)

        # - validate
        if isinstance(res, list):
            valid += 1
            if len(res) > 0:
                has_jobs += 1
                total_jobs += len(res)
            print(f'{i:<4} {slug:<40}           valid response              total: {len(res)}')
        else:
            invalid += 1
            print(f'{i:<4} {slug:<40}           invalid response            {res}')

        # - update
        results[slug] = res
        i += 1

        # respect rate limit
        time.sleep(0.2)
    end_time = time.time()

    # --- print stats
    print('-'*103)
    if i > 0:
        print(f'''scrape results:
    scraping time:        {end_time-start_time:.1f}s ({(end_time-start_time) / 60:.2f}m)
    scraped slugs:        {i}
    total jobs:           {total_jobs}
    -
    valid slugs:          {valid} ({(valid/i)*100:.1f}%)
    valid with jobs:      {has_jobs} 
    invalid:              {invalid} ({(invalid/i)*100:.1f}%)
''')
    else:
        print('no jobs scraped.')

    return results

def process_greenhouse_results(
        results: dict, 
        filepath: str='./greenhouse_jobs.csv'
    ) -> pd.DataFrame:

    df = pd.DataFrame(
        columns=[
            'slug', 'absolute_url', 'internal_job_id', 
            'company_name', 'requisition_id', 
            'title', 'first_published', 'language'],
    )

    # iterate through all slugs, and extract information from all valid job listings
    for slug in results.keys():
        jobs = results[slug]
        # process jobs
        if isinstance(jobs, list) and len(jobs) > 0:
            rows = []
            for job in jobs:
                data = {
                    'slug': slug, 
                    'absolute_url':     job['absolute_url'], 
                    'internal_job_id':  job['internal_job_id'], 
                    'company_name':     str(job['company_name']).strip(), 
                    'requisition_id':   job['requisition_id'], 
                    'title':            str(job['title']).strip().lower(), 
                    'first_published':  job['first_published'], 
                    'language':         str(job['language']).strip().lower(), 
                }
                rows.append(data)
            rows_df = pd.DataFrame(rows)
            df = pd.concat([df, rows_df], ignore_index=True)

    # add timestamp
    df['scrape_timestamp'] = pd.Timestamp.now(tz='UTC')
    # save as csv
    df.to_csv(filepath)
    return df

def process_greenhouse(
        df: pd.DataFrame,
        limit: int=-1,
        filepath: str='./greenhouse_jobs.csv'
    ) -> pd.DataFrame:
    results = scrape_greenhouse(df, limit)
    df = process_greenhouse_results(results, filepath)
    return df

In [54]:
process_greenhouse(greenhouse)

0    0verwatch                                          valid response              total: 1
1    103644278                                          valid response              total: 16
2    10alabs                                            valid response              total: 16
3    10beauty                                           valid response              total: 8
4    10xgenomics                                        invalid response            404 - job not found
5    12jlkfsk                                           valid response              total: 5
6    12twenty                                           valid response              total: 3
7    143studiosinc                                      valid response              total: 4
8    1456754456yhgbhfg                                  valid response              total: 1
9    14technology                                       valid response              total: 2
10   1800contacts                                       valid response              total: 11
11   1800gotjunk                                        valid response              total: 63
12   1848ventures                                       invalid response            404 - job not found
13   1910genetics                                       valid response              total: 6
14   1pyra                                              invalid response            404 - job not found
15   1uphealth                                          valid response              total: 0
16   204951305985924                                    valid response              total: 0
17   21shares                                           valid response              total: 1
18   240certification                                   valid response              total: 0
19   2k                                                 valid response              total: 125
20   2kearlycareers                                     valid response              total: 9
21   2kmadrid                                           valid response              total: 12
22   2u                                                 valid response              total: 2
23   2uinlinepromotions                                 valid response              total: 0
24   31stunion                                          valid response              total: 7
25   3cloud                                             valid response              total: 37
26   3dayblindscorporate                                valid response              total: 4
27   3dayblindsmanagementandsupport                     valid response              total: 15
28   3mgroofing                                         valid response              total: 28
29   3redpartners                                       valid response              total: 8
30   42northdental                                      valid response              total: 173
31   4lu44n1n37w012k                                    valid response              total: 13
32   4paws                                              valid response              total: 3
33   5364856uhdfnvbkldfnbhrpkdfgbdvtyhro                valid response              total: 1
34   540                                                valid response              total: 6
35   550                                                valid response              total: 29
36   5minlab                                            valid response              total: 2
37   5wpr                                               valid response              total: 6
38   60decibelsinc                                      valid response              total: 0
39   66degrees                                          valid response              total: 26
40   67streetdental                                     valid response              total: 0
41   6sense                                             valid response              total: 28
42   7shifts                                            valid response              total: 13
43   8451                                               valid response              total: 17
44   8451university                                     valid response              total: 0
45   86repairs                                          invalid response            404 - job not found
46   8thlightrebuild                                    valid response              total: 5
47   9thwayinsignia                                     valid response              total: 33
48   AptosLabs                                          valid response              total: 7
49   ArkoseLabs                                         valid response              total: 4
50   AviMedical                                         valid response              total: 34
51   Babylist                                           valid response              total: 44
52   BlankStreet                                        valid response              total: 99
53   Coast                                              valid response              total: 20
54   Convene                                            valid response              total: 41
55   DefenseUnicorns                                    valid response              total: 49
56   FiniteState                                        valid response              total: 10
57   Gitai                                              valid response              total: 17
58   Gradle                                             valid response              total: 7
59   Grover                                             valid response              total: 2
60   Halcyon                                            valid response              total: 8
61   HeyGen                                             valid response              total: 18
62   Karat                                              valid response              total: 11
63   LEX                                                valid response              total: 15
64   LOENBRO                                            valid response              total: 372
65   Legion                                             valid response              total: 16
66   Matik                                              valid response              total: 1
67   Merge                                              valid response              total: 0
68   Mill                                               valid response              total: 29
69   MobEntertainment                                   valid response              total: 10
70   MythicalGames                                      invalid response            404 - job not found
71   NozomiNetworks                                     valid response              total: 21
72   OKX                                                valid response              total: 329
73   OfferZen                                           valid response              total: 4
74   Profluent                                          valid response              total: 13
75   Pursuit                                            valid response              total: 11
76   QuellTherapeutics                                  valid response              total: 0
77   RapidSOS                                           valid response              total: 7
78   RedCellPartners                                    valid response              total: 21
79   Reltio                                             valid response              total: 31
80   Shift5                                             valid response              total: 15
81   ShopMy                                             valid response              total: 36
82   Smartling                                          valid response              total: 9
83   Splice                                             valid response              total: 7
84   Tamara                                             valid response              total: 32
85   ThreeFlow                                          valid response              total: 0
86   TogetherAI                                         valid response              total: 78
87   Trumid                                             valid response              total: 6
88   TwinHealth                                         valid response              total: 34
89   Upbound                                            valid response              total: 5
90   UrbanSportsClub                                    valid response              total: 4
91   VXServices                                         valid response              total: 2
92   ValeraHealth                                       valid response              total: 5
93   a1msolutions                                       valid response              total: 4
94   a24                                                valid response              total: 5
95   a3c41b8b71eff8c4                                   valid response              total: 6
96   aacpnw                                             valid response              total: 46
97   aavaa                                              valid response              total: 0
98   abacusfinancegroup                                 valid response              total: 0
99   abacusinsights                                     valid response              total: 11
100  abakaai                                            valid response              total: 10
101  abbyy                                              valid response              total: 7
102  abcellera                                          valid response              total: 32
103  abclabs                                            invalid response            404 - job not found
104  abilitypath                                        valid response              total: 10
105  abinbev                                            valid response              total: 58
106  able                                               valid response              total: 7
107  ably30                                             valid response              total: 5
108  abricareinc                                        valid response              total: 11
109  abrightbeginnings                                  valid response              total: 5
110  absherconstruction                                 valid response              total: 19
111  absolicsinc                                        valid response              total: 18
112  absolutesecurityintl                               valid response              total: 30
113  absurdventures                                     valid response              total: 17
114  accantohealth858accanto858                         valid response              total: 6
115  accela                                             valid response              total: 10
116  accelerationpartners                               valid response              total: 14
117  acceleronfusion                                    valid response              total: 1
118  accelschools                                       valid response              total: 243
119  accenturefederalservices                           valid response              total: 674
120  accesshealthca                                     valid response              total: 8
121  accessholdingsmanagementfirm                       valid response              total: 3
122  accesso                                            valid response              total: 5
123  accordion                                          valid response              total: 49
124  accreditedlabs                                     valid response              total: 34
125  accuweather                                        valid response              total: 16
126  aceable                                            valid response              total: 3
127  acentria                                           valid response              total: 7
128  achievementfirstnetworksupportcareers              valid response              total: 7
129  acilearning                                        valid response              total: 6
130  aclu                                               valid response              total: 20
131  acluinternships                                    valid response              total: 43
132  aclunc                                             valid response              total: 6
133  aclunj                                             valid response              total: 11
134  acog                                               valid response              total: 6
135  acommerce                                          valid response              total: 72
136  acornhealth                                        valid response              total: 109
137  acquia                                             valid response              total: 10
138  acrisureinnovation                                 invalid response            404 - job not found
139  acryldata                                          valid response              total: 7
140  act1federal                                        valid response              total: 48
141  action                                             valid response              total: 11
142  actpowerservices                                   valid response              total: 55
143  acuitymd                                           valid response              total: 11
144  acumen                                             valid response              total: 1
145  acutechgroupinc                                    valid response              total: 12
146  ada18                                              valid response              total: 10
147  adahealth                                          valid response              total: 0
148  adamsclinical                                      valid response              total: 39
149  adapter                                            valid response              total: 4
150  adaptivewater                                      invalid response            404 - job not found
151  adaugeohealthcare                                  valid response              total: 1
152  addepar1                                           valid response              total: 98
153  adeedo                                             valid response              total: 1
154  adelphicommunications                              valid response              total: 0
155  adelphigraduatecareers                             valid response              total: 0
156  adelphigrouplimited                                valid response              total: 0
157  adelphiresearch                                    valid response              total: 0
158  adelphivaluesproveuk                               valid response              total: 0
159  adfinternational                                   valid response              total: 2
160  adicettherapeuticsinc                              valid response              total: 5
161  aditumbio                                          valid response              total: 4
162  adjustjobs                                         valid response              total: 14
163  administrative                                     valid response              total: 0
164  admios                                             valid response              total: 3
165  adswerveinc                                        valid response              total: 5
166  adultservices                                      valid response              total: 6
167  advancedspace                                      valid response              total: 19
168  advancedtechnologyservices                         valid response              total: 117
169  advertisingspecialtyinstitute                      valid response              total: 7
170  advocateconstruction                               valid response              total: 0
171  advocatesforchildrenofnewyork                      valid response              total: 2
172  advocateslawcareers                                valid response              total: 3
173  adyen                                              valid response              total: 206
174  aechelontechnology                                 valid response              total: 21
175  aef                                                valid response              total: 0
176  aegisventures                                      valid response              total: 12
177  aegworldwide                                       valid response              total: 164
178  aerospike                                          invalid response            404 - job not found
179  aestudio                                           valid response              total: 7
180  aevexaerospace                                     valid response              total: 62
181  aeyeinc                                            valid response              total: 3
182  afcvolunteers                                      valid response              total: 1
183  affinidi                                           valid response              total: 6
184  affinitiv                                          valid response              total: 4
185  affinity                                           invalid response            404 - job not found
186  affirm                                             valid response              total: 174
187  affirmedrxpbc                                      valid response              total: 8
188  affordablepetcareatfourcorners                     valid response              total: 0
189  afresh                                             valid response              total: 12
190  ag1                                                valid response              total: 6
191  agebold                                            valid response              total: 6
192  agecareers                                         valid response              total: 60
193  agency                                             valid response              total: 832
194  agencywithin                                       valid response              total: 58
195  ageoflearninginc                                   valid response              total: 10
196  agibank                                            valid response              total: 130
197  agibankvagasfuturas                                valid response              total: 37
198  agilesix                                           valid response              total: 0
199  agilisys                                           valid response              total: 4
200  agilize                                            valid response              total: 6
201  agoda                                              valid response              total: 291
202  agri-access                                        valid response              total: 3
203  agwestfarmcredit                                   valid response              total: 16
204  ahrefsjobs                                         valid response              total: 15
205  aidashinc                                          valid response              total: 9
206  aidocmedical                                       valid response              total: 32
207  aiedu                                              valid response              total: 4
208  aifoundry                                          valid response              total: 3
209  aift                                               valid response              total: 27
210  aiologic                                           valid response              total: 3
211  aipn                                               valid response              total: 12

,slug,absolute_url,internal_job_id,company_name,requisition_id,title,first_published,language,scrape_timestamp
0,0verwatch,https://job-boards.greenhouse.io/0verwatch/job...,4175494009,0verwatch,11,full stack engineer,2026-06-26T14:54:10-04:00,en,2026-09-28 23:24:06.225181+00:00
1,103644278,https://job-boards.greenhouse.io/103644278/job...,3529091,Lume Deodorant,1977,"associate creative director, art director",2026-08-24T16:50:22-04:00,en,2026-09-28 23:24:06.225181+00:00
2,103644278,https://job-boards.greenhouse.io/103644278/job...,3488538,Lume Deodorant,1953,"associate creative director, copywriter",2026-07-07T12:37:12-04:00,en,2026-09-28 23:24:06.225181+00:00
3,103644278,https://job-boards.greenhouse.io/103644278/job...,3505581,Lume Deodorant,1964,head of tiktok shop,2026-07-28T12:32:03-04:00,en,2026-09-28 23:24:06.225181+00:00
4,103644278,https://job-boards.greenhouse.io/103644278/job...,3549548,Lume Deodorant,1984,"influencer marketing manager, lume and mando",2026-09-14T13:50:50-04:00,en,2026-09-28 23:24:06.225181+00:00
...,...,...,...,...,...,...,...,...,...
151018,zyngacareers,https://job-boards.greenhouse.io/zyngacareers/...,5215617004,Zynga,R_118688,user acquisition manager,2026-09-16T02:20:02-04:00,en,2026-09-28 23:24:06.225181+00:00
151019,zyngacareers,https://job-boards.greenhouse.io/zyngacareers/...,5219238004,Zynga,R_118727,vip account manager,2026-09-22T11:13:58-04:00,en,2026-09-28 23:24:06.225181+00:00
151020,zyngaearlycareers,https://job-boards.greenhouse.io/zyngaearlycar...,5215618004,Zynga Early Careers,R_118698,marketing artist intern,2026-09-17T11:50:31-04:00,en,2026-09-28 23:24:06.225181+00:00
151021,zyngaearlycareers,https://job-boards.greenhouse.io/zyngaearlycar...,5214860004,Zynga Early Careers,R_118724,rotational product manager - canada,2026-09-15T13:26:47-04:00,en,2026-09-28 23:24:06.225181+00:00
151022,zyngaearlycareers,https://job-boards.greenhouse.io/zyngaearlycar...,5215022004,Zynga Early Careers,R_118730,rotational product manager - united states,2026-09-15T13:24:40-04:00,en,2026-09-28 23:24:06.225181+00:00

In [56]:
sm = pd.read_csv('../ats_companies/smartrecruiters.csv')
sm.head()

                   slug
0  10xValuePartnersGmbH
1              1839Labs
2               1HUDDLE
3               1Huddle
4         1perTInentInc

In [64]:
res = requests.get('https://api.smartrecruiters.com/v1/companies/1huddle/postings')

In [65]:
res.json()['content']

[{'id': '744000056465632',
  'name': 'Associate, Internship Team',
  'uuid': 'b4bf7a54-c438-4e39-aedd-32f156894b4e',
  'jobAdId': '353f4b98-0e8c-4c46-ab92-8dac6a53e5cf',
  'defaultJobAd': True,
  'refNumber': 'REF7R',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2025-04-29T17:58:57.823Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'business_development', 'label': 'Business Development'},
  'typeOfEmployment': {'id': 'intern', 'label': 'Intern'},
  'experienceLevel': {'id': 'internship', 'label': 'Internship'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/744000056465632',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999796389573',
  'name': 'Account Executive, Sales',
  'uuid': '026bdcf5-63b8-4e69-8eb4-70de94ca2d23',
  'jobAdId': 'dbd48082-49a1-4437-b71f-4a3ed85698bb',
  'defaultJobAd': True,
  'refNumber': 'REF16Y',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2022-01-04T20:15:29.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'sales', 'label': 'Sales'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'entry_level', 'label': 'Entry Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999796389573',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999794264574',
  'name': 'Solutions Architect',
  'uuid': '3c55dcfb-dbd2-4b58-9042-51d5286d5993',
  'jobAdId': '7d8630a2-d8fb-4322-8382-a3b4d878eee7',
  'defaultJobAd': True,
  'refNumber': 'REF25E',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-12-22T20:09:02.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'engineering', 'label': 'Engineering'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'mid_senior_level', 'label': 'Mid-Senior Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999794264574',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999794259788',
  'name': 'Manager, Customer Success',
  'uuid': '7861f612-3c24-4b0e-8ab4-1749cc37bb1c',
  'jobAdId': '79f62876-8218-4746-8563-5d6fadb0f5a7',
  'defaultJobAd': True,
  'refNumber': 'REF15Y',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-12-22T19:49:26.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'customer_service', 'label': 'Customer Service'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'mid_senior_level', 'label': 'Mid-Senior Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999794259788',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999794061243',
  'name': 'Enterprise Account Executive, Sales',
  'uuid': '8de12be8-e0e5-4e5c-b60a-e06f9fcc34f9',
  'jobAdId': '083a62b6-d271-471a-a1bd-ea710be8bb60',
  'defaultJobAd': True,
  'refNumber': 'REF20U',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-12-21T17:52:21.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'business_development', 'label': 'Business Development'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'mid_senior_level', 'label': 'Mid-Senior Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999794061243',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999794057292',
  'name': 'Customer Success Rep',
  'uuid': '05e6bab7-69a1-4fe2-b0a1-3a6faa0dc146',
  'jobAdId': 'd6fb2fe6-f708-4f34-a4bc-81c31ee54954',
  'defaultJobAd': True,
  'refNumber': 'REF24Z',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-12-21T17:27:26.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'customer_service', 'label': 'Customer Service'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'entry_level', 'label': 'Entry Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999794057292',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999773892926',
  'name': 'Graphic Designer',
  'uuid': '5d46f28e-968e-46e3-8206-5955ce1b3db0',
  'jobAdId': '916d0bf3-81fb-4141-a1dd-90293947a572',
  'defaultJobAd': True,
  'refNumber': 'REF21F',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-09-16T20:02:25.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'design', 'label': 'Design'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'entry_level', 'label': 'Entry Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999773892926',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999773892333',
  'name': 'Instructional Designer',
  'uuid': 'd40bff0a-53e5-4566-89ac-47e238acdeec',
  'jobAdId': '598de157-ccde-4f6b-bdbd-49d6ba731e88',
  'defaultJobAd': True,
  'refNumber': 'REF23G',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2021-09-16T20:00:39.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'writing_editing', 'label': 'Writing/Editing'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'entry_level', 'label': 'Entry Level'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999773892333',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}},
 {'id': '743999702370312',
  'name': 'Growth Marketer',
  'uuid': '4ce9c857-86ea-447b-bb93-4828b2afe57c',
  'jobAdId': 'cf3bc001-0d36-444f-bea9-8139ec8c9963',
  'defaultJobAd': True,
  'refNumber': 'REF22Z',
  'company': {'identifier': '1Huddle', 'name': '1Huddle'},
  'releasedDate': '2019-12-18T13:43:10.000Z',
  'location': {'city': 'Newark',
   'region': 'NJ',
   'country': 'us',
   'address': '550 Broad Street',
   'postalCode': '07102',
   'remote': False,
   'hybrid': False,
   'latitude': '40.7425757',
   'longitude': '-74.1687227',
   'fullLocation': 'Newark, NJ, United States'},
  'industry': {'id': 'computer_software', 'label': 'Computer Software'},
  'department': {},
  'function': {'id': 'marketing', 'label': 'Marketing'},
  'typeOfEmployment': {'id': 'permanent', 'label': 'Full-time'},
  'experienceLevel': {'id': 'executive', 'label': 'Executive'},
  'customField': [{'fieldId': 'COUNTRY',
    'fieldLabel': 'Country/Region',
    'valueId': 'us',
    'valueLabel': 'United States'},
   {'fieldId': '58b7e892e4b09a6d37a0d5df',
    'fieldLabel': 'Brands',
    'valueId': 'default',
    'valueLabel': '1Huddle'}],
  'visibility': 'PUBLIC',
  'ref': 'https://api.smartrecruiters.com/v1/companies/1huddle/postings/743999702370312',
  'creator': {'name': 'Brianna Hernandez'},
  'language': {'code': 'en',
   'label': 'English',
   'labelNative': 'English (US)'}}]

In [62]:
res2 = requests.get('https://api.smartrecruiters.com/v1/companies/1HUDDLE/postings/744000056465632')

In [63]:
res2.json()

{'id': '744000056465632',
 'name': 'Associate, Internship Team',
 'uuid': 'b4bf7a54-c438-4e39-aedd-32f156894b4e',
 'jobId': '4fd2fe3a-f3bd-4798-b4ef-75661bd2c6d6',
 'jobAdId': '353f4b98-0e8c-4c46-ab92-8dac6a53e5cf',
 'defaultJobAd': True,
 'refNumber': 'REF7R',
 'company': {'name': '1Huddle', 'identifier': '1Huddle'},
 'location': {'city': 'Newark',
  'region': 'NJ',
  'country': 'us',
  'address': '550 Broad Street',
  'postalCode': '07102',
  'remote': False,
  'hybrid': False,
  'latitude': '40.7425757',
  'longitude': '-74.1687227',
  'fullLocation': 'Newark, NJ, United States'},
 'customField': [{'fieldId': 'COUNTRY',
   'fieldLabel': 'Country/Region',
   'valueId': 'us',
   'valueLabel': 'United States'},
  {'fieldId': '58b7e892e4b09a6d37a0d5df',
   'fieldLabel': 'Brands',
   'valueId': 'default',
   'valueLabel': '1Huddle'}],
 'releasedDate': '2025-04-29T17:58:57.823Z',
 'creator': {'name': 'Brianna Hernandez',
  'avatarUrl': 'https://c.smartrecruiters.com/sr-employee-image-prod-aws-dc5/517481d2e4b04221b4912df9?r=s3-eu-central-1&_1553182612001'},
 'postingUrl': 'https://jobs.smartrecruiters.com/1Huddle/744000056465632-associate-internship-team',
 'applyUrl': 'https://jobs.smartrecruiters.com/1Huddle/744000056465632-associate-internship-team?oga=true',
 'referralUrl': 'https://jobs.smartrecruiters.com/external-referrals/company/1Huddle/publication/b4bf7a54-c438-4e39-aedd-32f156894b4e?dcr_ci=1Huddle',
 'jobAd': {'sections': {'companyDescription': {'title': 'Company Description',
    'text': '<p>Today, companies spend huge amounts of time &amp; money on training that is outdated, boring and quickly forgotten by employees. With our game based training platform companies convert boring training material into competitive training games that are proven to increase sales performance. 1Huddle engages employees through daily training games that companies can customize to their brand and be&#xa0;played in under 5 minutes a day.</p><p>Clients including: Audible, TAO Group, Madison Square Garden, Golden State Warriors, Hand and Stone, New York Mets, Fossil Group, US Air Force, Loews Hotels and more.<br>\n<br>\nWe power the people that power teams. Featured on Fox News, CNN, Huff Post, Bloomberg &amp; The Wall Street Journal.</p>'},
   'jobDescription': {'title': 'Job Description',
    'text': '<p>The company is currently seeking candidates for our development-based Unpaid Internship Program. Positions are available in the 1Huddle HQ in Newark, NJ.</p><p><strong>Current Internship Roles</strong>: Candidates will commit to an intensive internship track in one of the following business divisions:</p><ul><li>Sales</li><li>Coaching Staff/Game Design</li><li>Product/QA Associate</li><li>Marketing</li></ul><p><strong>Primary Duties and Responsibilities - Sales:</strong></p><ul><li>Direct Sales for a variety of events</li><li>Call current, new and past sales leads to generate sales</li><li>Attend team and community events for the purpose of maximizing sales and service opportunities</li></ul><p><strong>Primary Duties and Responsibilities - Coaching Staff:</strong></p><ul><li>Manage coaching staff process with existing 1Huddle&#xa0;Clients</li><li>Game Operations: support for existing 1Huddle training clients</li></ul><p><strong>Primary Duties and Responsibilities -&#xa0;Product/QA:</strong></p><ul><li><p>Web-based, Android, iOS</p></li><li><p>Test and detect issues/bugs in potential new features or updates</p></li><li><p>Work on improving and maintaining testing process</p></li><li><p>User acceptance, compatibility, and accessibility testing</p></li><li><p>Product/market research and analysis</p></li><li><p>Provide usability feedback in response to requirements and design of features</p></li><li><p>Detail oriented</p></li><li><p>Strong analytical skills</p></li></ul><p><strong>Primary Duties and Responsibilities - Marketing</strong></p><ul><li>Assist with day to day operations of social media</li><li>Complete vendor and market research</li><li>Assist with video and marketing campaign operations</li></ul><p><strong>General</strong></p><ul><li>Ability to work in a dynamic team environment with all levels in the organization</li><li>Act proactively to create opportunities for new business with existing customers</li><li>Research and develop new business initiatives</li></ul>'},
   'qualifications': {'title': 'Qualifications',
    'text': '<p><strong>The ideal candidate will have:</strong></p><ul><li>Have a friendly and professional telephone manner</li><li>Display an outstanding ability to listen well</li><li>Advanced skills in Powerpoint, Word and Excel.</li><li>Proficient in functions of social media platforms such as Twitter, Facebook and LinkedIn.</li><li>Work well in a team environment</li><li>Effectively express ideas verbally and in writing</li><li>Independently take action beyond what is called for</li><li>Demonstrate a positive attitude</li></ul><p><strong>Experience:</strong> No previous professional sales experience required.</p><ul><li>The position reports to the Executive Leadership team.</li><li>Equal Opportunity Employer.</li><li>All your information will be kept confidential according to EEO guidelines.</li></ul>'},
   'additionalInformation': {'title': 'Additional Information',
    'text': '<p>The interview process at 1Huddle is as follows:</p><ul><li>Phase 1: Submit Application with Cover Letter + Resume. (Complete)</li><li>Phase 2: Brief Call to introduce yourself, and for us to introduce 1Huddle.</li><li>Phase 3: Meeting with member of Leadership Team or CEO. Our final check to ensure you’re qualified, capable and ready to win at 1H.</li></ul><p>Our process is structured to allow a candidate’s personality to shine through in the first few rounds, making it easier for our team to determine who would be a good fit at 1Huddle. Are you up to the challenge?</p>'},
   'videos': {'title': 'Videos To Watch',
    'urls': ['https://www.youtube.com/watch?v=jB5bJb0Kay0&feature=youtu.be']}}},
 'active': True,
 'visibility': 'PUBLIC',
 'industry': {'id': 'computer_software', 'label': 'Computer Software'},
 'function': {'id': 'business_development', 'label': 'Business Development'},
 'experienceLevel': {'id': 'internship', 'label': 'Internship'},
 'typeOfEmployment': {'id': 'intern', 'label': 'Intern'},
 'language': {'code': 'en', 'label': 'English', 'labelNative': 'English (US)'}}