# Introduction
This notebook contains a record of different **ATS systems**, and their URL structures. Some ATS
systems are simple to understand, while others are more complicated. To keep this project managable,
and to create a running proof-of-concept, we will use a small subset of our desired scope of ATS systems.

## ATS System Notes

Below is a simple text cell containing notes on different ATS systems.

```text
-- oracle
URLS:
    https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs
    https://fa-euwp-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs
    https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs
    https://eofe.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/BNY-Careers/jobs
explained:
    jpmc                    tenant
    CX_1001                 directories under the tenant, for example jpmc (J.P. Morgan Chase) has
                            CX_1001 (J.P. Morgan Chase) and CX_1003 (Chase Bank)
notes:
    all of these UIs look very different.

-- workday
URLS:
    https://ally.wd1.myworkdayjobs.com/en-US/Ally
    https://cat.wd5.myworkdayjobs.com/en-US/CaterpillarCareers
    https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays/jobs
explained:
    ally                    tenant
    wd1                     datacenter
notes:
    you can add /jobs at the end and find the same result

    https://wd1.myworkdaysite.com/recruiting/wf/WellsFargoJobs/jobs - perhaps an older version (TODO)

-- smartrecruiters
URLS:
    https://careers.smartrecruiters.com/Wavestone1/
    https://careers.smartrecruiters.com/PAConsulting/
notes:
    it seems that careers holds the job directory, while jobs.smartrecruiters has the actual jobs

-- ashby
URLS:
    https://jobs.ashbyhq.com/gecko-robotics/

-- eightfold.ai
URLS:
    https://careers.elcompanies.com/careers?start=0&pid=1168275629602&sort_by=hot
    https://careers.deere.com/careers?start=0&pid=137477597562&sort_by=hot
explained:
    careers.{company}.com       eightfold tenant
notes:
    ones which are eightfold look like this typically. they have this careers?start={N}&pid={pid}
    section

-- icims
    https://careers-libertymutual.icims.com/jobs/search?ss=1&searchRelation=keyword_all
    https://us-erac.icims.com/jobs/search?ss=1
explained:
    careers-libertymutual       tenant
notes:
    include the careers section, as there are many examples which use careers-{name}.icims, as well as 
    examples with simply {name}.icims

-- Taleo (TODO)
    https://phf.tbe.taleo.net/phf02/ats/careers/v2/searchResults?org=ADELPHI&cws=43

-- other
https://careers.ibm.com/en_US/careers/
https://delta.avature.net/en_US/careers/
there is a pattern to be uncovered with ones that look like this
https://www.careers.jnj.com/en/jobs
https://jobs.siemens.com/en_US/externaljobs/SearchJobs/?listFilterMode=1&folderRecordsPerPage=6&
https://careers.homedepot.com/job-search-results/
```

# ATS System Structure as CSV
We will turn the structure into a simple CSV for viewing.

In [1]:
import pandas as pd

# TODO below are ATS systems not yet incorporated:
# Oracle
# Paylocity - recruiting.paylocity.com/Recruiting/Jobs/All/{companyId}
# Teamtailor - {slug}.teamtailor.com
# Eightfold.ai - careers.{company}.com
# iCims - {token}.icims.com

# TODO ATS systems with issues when scraping
# Lever - weird crawl results - jobs.lever.co/{slug}

data = [
    ['greenhouse', 'job-boards.greenhouse.io/{slug}'],
    ['greenhouse', 'boards.greenhouse.io/{slug}'],

    ['ashby', 'jobs.ashbyhq.com/{slug}'],

    ['smartrecruiters', 'careers.smartrecruiters.com/{slug}'], # note that job postings are stored in jobs.smartrecruiters.com

    ['recruitee', '{slug}.recruitee.com'],

    ['breezyhr', '{slug}.breezy.hr'],

    ['workday', '{company}.wd{N}.myworkdayjobs.com/{slug}'], # fuck you workday
]

df = pd.DataFrame(data, columns=['ats_system', 'url'])
df

        ats_system                                      url
0       greenhouse          job-boards.greenhouse.io/{slug}
1       greenhouse              boards.greenhouse.io/{slug}
2            ashby                  jobs.ashbyhq.com/{slug}
3  smartrecruiters       careers.smartrecruiters.com/{slug}
4        recruitee                     {slug}.recruitee.com
5         breezyhr                         {slug}.breezy.hr
6          workday  {tenant}.wd{N}.myworkdayjobs.com/{site}

In [7]:
# for testing ATS urls:

!cdxt --limit 100 --crawl 1 iter --csv "*.myworkdayjobs.com/*"

status,timestamp,url
200,20260917000735,https://randstad.impl-wd502.myworkdayjobs.com/robots.txt
200,20260910104126,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Alabaster-AL/Wireless-Sales_REQ_104461
200,20260910093631,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Albuquerque-NM/HP-Retail-Sales-Representative_REQ_107276
200,20260910110034,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Alexander-City-AL/Wireless-Sales_REQ_104880-1
200,20260909222101,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Amarillo-TX/HP-PC-Sales-Representative_REQ_100928
200,20260910110301,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Andalusia-AL/Wireless-Sales_REQ_104457
200,20260910104905,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Annapolis-MD/Chromebook-Sales-Specialist_REQ_106737
200,20260910104746,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Arlington-TX/Market-Manager_REQ_108269
200,20260910105511,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Arlington-TX/Retail-Sales-Associate_REQ_107769
200,20260910110921,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Atlanta-GA/Retail-Engagement-Specialist_REQ_107133-1
200,20260910104223,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Austin-TX/Samsung-Field-Sales-Manager_REQ_108456
200,20260910101228,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bay-Shore-NY/HP-Retail-Sales-Representative_REQ_107011
200,20260909224142,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Energy-Sales-Specialist_REQ_094769
200,20260909222947,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Energy-Sales-Specialist_REQ_094775
200,20260916212128,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Energy-Sales-Specialist_REQ_096520
200,20260916205906,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Retail-Sales-Associate_REQ_083788
200,20260909223010,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Retail-Sales-Associate_REQ_083789
200,20260910194012,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Retail-Sales-Associate_REQ_092313
200,20260910192435,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Retail-Sales-Associate_REQ_097353
200,20260909224105,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Bilingual-Samsung-Ticket-Operations-Coordinator--Korean-English_REQ_100133
200,20260916222400,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Brand-Ambassador_REQ_089835
200,20260910103942,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Brewton-AL/Part-Time-Wireless-Sales_REQ_105083
200,20260910094647,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Burbank-IL/HP-Retail-Sales-Representative_REQ_108994
200,20260910093954,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Canoga-Park-CA/HP-PC-Sales-Representative_REQ_107532
200,20260910095902,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Cerritos-CA/Samsung-Sales-Specialist--Part-Time_REQ_108887
200,20260910103916,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Charleston-SC/HP-Retail-Sales-Representative_REQ_108404
200,20260910110151,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Chicago-Heights-IL/Retail-Sales-Representative_REQ_108387
200,20260910195122,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Chromebook-Sales-Specialist_REQ_089281
200,20260910103726,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Chula-Vista-CA/Bilingual-Samsung-Experience-Consultant_REQ_108650
200,20260910102651,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Cicero-IL/Retail-Sales-Representative_REQ_108600
200,20260916220115,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Clarion-PA/Retail-Sales-Associate_REQ_099153
200,20260910110059,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/College-Station-TX/HP-Retail-Sales-Representative_REQ_108908
200,20260914020222,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Columbus-GA/Wireless-Sales_REQ_095361
200,20260910194157,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Conshohocken-PA/Retail-Sales_REQ_101195
200,20260910105223,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Crawfordville-FL/Wireless-Sales_REQ_108867
200,20260910100616,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Cullman-AL/Wireless-Sales_REQ_106961
200,20260909221758,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Dallas-TX/Territory-Manager_REQ_100675
200,20260910100454,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Davenport-IA/Chromebook-Sales-Specialist_REQ_107518
200,20260910103436,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Dayton-OH/Retail-Sales-Associate_REQ_107013-1
200,20260910105919,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Dayton-OH/Sales-Representative_REQ_104567-1
200,20260916222111,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Dell-Territory-Sales-Representative_REQ_096595
200,20260910101400,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Dublin-CA/Chromebook-Sales-Specialist_REQ_108686-1
200,20260910104839,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Edinburg-TX/Bilingual-Retail-Sales-Associate_REQ_107270
200,20260910095738,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Elkridge-MD/Meta-Sales-Specialist_REQ_108233
200,20260910095354,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Elmhurst-NY/Samsung-Inventory-Control-Specialist--Part-Time_REQ_106889
200,20260910102223,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Elsa-TX/Bilingual-Retail-Sales-Associate_REQ_107271
200,20260910194633,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Energy-Sales-Specialist_REQ_094754
200,20260910191942,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Energy-Sales-Specialist_REQ_096988
200,20260910104153,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Fairhope-AL/Part-Time-Wireless-Sales_REQ_102601
200,20260910103213,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Farmington-NM/Retail-Display-Installer---Technology_REQ_107150
200,20260910093252,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Fayetteville-NC/Meta-Sales-Specialist_REQ_109006
200,20260910103629,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Fort-Lauderdale-FL/Meta-Sales-Specialist_REQ_108061
200,20260910100736,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Fort-Worth-TX/Territory-Sales-Representative_REQ_108434
200,20260909223943,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Full-Time-Territory-Sales-Representative_REQ_088737
200,20260910095421,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Glen-Burnie-MD/Retail-Engagement-Specialist_REQ_109036
200,20260910102841,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Grove-City-PA/Retail-Sales-Representative_REQ_108605
200,20260910100549,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Gulf-Shores-AL/Wireless-Sales_REQ_106667
200,20260910110007,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Harlingen-TX/Bilingual-Retail-Sales-Associate_REQ_102371
200,20260910103408,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Harlingen-TX/Bilingual-Retail-Sales-Associate_REQ_104498
200,20260909224944,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Hatfield-PA/Sales-Representative_REQ_098994
200,20260909213225,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Hialeah-FL/HP-Retail-Sales-Representative_REQ_099924
200,20260910100029,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Houston-TX/Android-Sales-Expert_REQ_106263
200,20260910095612,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Houston-TX/Samsung-Inventory-Control-Specialist--Part-Time_REQ_106778-1
200,20260909215630,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/HP-Retail-Sales-Representative_REQ_096380
200,20260909214301,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/HP-Retail-Sales-Representative_REQ_097126
200,20260909224841,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/HP-Retail-Sales-Representative_REQ_101888
200,20260910095326,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Irving-TX/Bilingual-Retail-Sales-Associate_REQ_108840
200,20260910101846,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Jacksonville-FL/HP-Retail-Sales-Representative_REQ_107326-1
200,20260910110915,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Jacksonville-FL/Meta-Sales-Specialist_REQ_107558
200,20260910105649,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Jersey-City-NJ/Meta-Sales-Specialist_REQ_107543
200,20260910110349,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Johnson-City-TN/HP-PC-Sales-Representative_REQ_105874
200,20260910110643,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Kansas-City-KS/Territory-Manager_REQ_071633
200,20260910104656,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Kent-OH/Retail-Sales-Representative_REQ_108964
200,20260910104256,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Lakewood-NJ/Retail-Display-Installer---Technology_REQ_107146
200,20260910103339,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Laredo-TX/Bilingual-Retail-Sales-Associate_REQ_071761
200,20260910110728,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Las-Vegas-NV/Meta-Sales-Specialist_REQ_109001
200,20260910104630,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Laurel-MD/HP-PC-Sales-Representative_REQ_108984
200,20260914023131,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Lead-Samsung-Experience-Consultant_REQ_100759
200,20260910093900,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Madison-AL/Wireless-Sales_REQ_107090
200,20260909222031,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Maineville-OH/Sales-Representative_REQ_099036-1
200,20260910104931,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Manchester-CT/HP-PC-Sales-Representative_REQ_108988-1
200,20260910100351,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Manchester-NH/Chromebook-Sales-Specialist_REQ_106866-1
200,20260910100425,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Massillon-OH/Sales-Representative_REQ_101653
200,20260916221420,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Mcdonough-GA/Retail-Sales_REQ_097011
200,20260910101803,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Mesa-AZ/Chromebook-Sales-Specialist_REQ_108486
200,20260910191921,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Meta-Brand-Ambassador_REQ_089127
200,20260910195631,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Meta-Brand-Ambassador_REQ_089220
200,20260910103822,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Miami-FL/HP-Retail-Sales-Representative_REQ_108638
200,20260910110441,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Millbrook-AL/Wireless-Sales_REQ_106393-1
200,20260910110530,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Minneapolis-MN/Full-Time-Retail-Display-Installer--Technology_REQ_109017
200,20260910101507,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Minneapolis-MN/HP-Retail-Sales-Representative_REQ_107000
200,20260910110906,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Montgomery-IL/Retail-Sales-Representative_REQ_106975
200,20260910104722,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Myrtle-Beach-SC/HP-Retail-Sales-Representative_REQ_106558
200,20260910110553,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Nashville-TN/Google-TV-Experience-Manager_REQ_108318
200,20260910194547,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/New-Lenox-IL/Sales-Representative_REQ_098188
200,20260910102949,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/New-York-NY/HP-Retail-Sales-Representative_REQ_108986
200,20260910110126,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Newark-NJ/Merchant-Regional-Manager_REQ_107803
200,20260910093754,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Okemos-MI/HP-Retail-Sales-Representative_REQ_108748
200,20260910105829,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Oneonta-AL/Wireless-Sales_REQ_106798
200,20260916212701,https://2020companies.wd1.myworkdayjobs.com/en-US/External_Careers/job/Part-Time-Wireless-Sales_REQ_077549

In [3]:
## CC INDEX OUTPUT EXAMPLE -- USING THE FOLLOWING QUERY:

# SELECT
#     *
# FROM "ccindex"."ccindex"
# WHERE 
#     crawl = 'CC-MAIN-2026-39'
#     AND subset = 'warc'
# LIMIT 10;

In [4]:
q = pd.read_csv('./crawl_result.csv')
q

,url_surtkey,url,url_host_name,url_host_tld,url_host_2nd_last_part,url_host_3rd_last_part,url_host_4th_last_part,url_host_5th_last_part,url_host_registry_suffix,url_host_registered_domain,...,content_charset,content_languages,content_truncated,warc_record_id,warc_filename,warc_record_offset,warc_record_length,warc_segment,crawl,subset
0,"io,tackle)/tackle-platform/alliances",https://tackle.io/tackle-platform/alliances/,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 e6 e7 b4 7e cc b9 39 37 38 20 61 16 cc,crawl-data/CC-MAIN-2026-39/segments/1788492995...,450673084,45991,1.788493e+12,CC-MAIN-2026-39,warc
1,"io,tackle)/tackle-platform/founder-ceo",https://tackle.io/tackle-platform/founder-ceo/,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 ad d8 51 70 4b b8 65 d4 c4 c0 56 2b 46,crawl-data/CC-MAIN-2026-39/segments/1788492995...,480134428,46228,1.788493e+12,CC-MAIN-2026-39,warc
2,"io,tackle)/tackle-platform/prospect",https://tackle.io/tackle-platform/prospect/,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 7b 89 89 73 21 96 ab 35 5f 26 8c 57 c7,crawl-data/CC-MAIN-2026-39/segments/1788492995...,470277239,45974,1.788493e+12,CC-MAIN-2026-39,warc
3,"io,tackle)/tackle-platform/revenue-operations?...",https://tackle.io/tackle-platform/revenue-oper...,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 ac f6 cc 79 93 ae e8 4b cc c8 b8 d9 43,crawl-data/CC-MAIN-2026-39/segments/1788492995...,462682091,44912,1.788493e+12,CC-MAIN-2026-39,warc
4,"io,tackle)/tackle-platform?utm_source=chatgpt.com",https://tackle.io/tackle-platform/?utm_source=...,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 87 5c 60 7a 23 95 f6 df b5 7c b7 4a fc,crawl-data/CC-MAIN-2026-39/segments/1788492995...,461684450,47902,1.788493e+12,CC-MAIN-2026-39,warc
5,"io,tackle)/topics/marketplace-news/page/2",https://tackle.io/topics/marketplace-news/page/2/,tackle.io,io,tackle,NaN,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 a5 8d 71 11 76 e3 8f c2 01 ee ea 68 4a 63,crawl-data/CC-MAIN-2026-39/segments/1788492995...,508616931,41859,1.788493e+12,CC-MAIN-2026-39,warc
6,"io,tackle,developers)/docs/getting-started",https://developers.tackle.io/docs/getting-started,developers.tackle.io,io,tackle,developers,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 8a f4 70 99 71 1e 94 7a a8 bb 43 ef b2 4c,crawl-data/CC-MAIN-2026-39/segments/1788492699...,144427054,34781,1.788493e+12,CC-MAIN-2026-39,warc
7,"io,tackle,developers)/docs/getting-started-wit...",https://developers.tackle.io/docs/getting-star...,developers.tackle.io,io,tackle,developers,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 8a f8 b4 45 7f 83 a7 2b 4e e4 55 01 52 ef,crawl-data/CC-MAIN-2026-39/segments/1788492699...,165983486,37181,1.788493e+12,CC-MAIN-2026-39,warc
8,"io,tackle,developers)/docs/getting-started?utm...",https://developers.tackle.io/docs/getting-star...,developers.tackle.io,io,tackle,developers,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 8a cb 7a 9d 75 22 86 f2 1a bd f9 01 53 e2,crawl-data/CC-MAIN-2026-39/segments/1788492699...,158515143,34814,1.788493e+12,CC-MAIN-2026-39,warc
9,"io,tackle,developers)/docs/how-to-get-an-m2m-c...",https://developers.tackle.io/docs/how-to-get-a...,developers.tackle.io,io,tackle,developers,NaN,NaN,io,tackle.io,...,UTF-8,eng,NaN,01 a0 8a eb 6c f2 72 c3 bf fe 30 68 08 26 fd 94,crawl-data/CC-MAIN-2026-39/segments/1788492699...,154968237,34508,1.788493e+12,CC-MAIN-2026-39,warc